#!/usr/bin/env python3
"""Generates src/tokenizer/unicode_tables.cpp: sorted, merged codepoint ranges for
the three Unicode classes Qwen's pre-tokenizer pattern uses: \\p{L}, \\p{N} and \\s.

Usage: python3 tools/gen_unicode_tables.py > src/tokenizer/unicode_tables.cpp
"""
import unicodedata

# The White_Space property (Unicode PropList.txt), which regex engines use for \s.
# Python's unicodedata does not expose it; the set has been stable since Unicode 6.0.
WHITE_SPACE = [
    (0x0009, 0x000D), (0x0020, 0x0020), (0x0085, 0x0085), (0x00A0, 0x00A0),
    (0x1680, 0x1680), (0x2000, 0x200A), (0x2028, 0x2029), (0x202F, 0x202F),
    (0x205F, 0x205F), (0x3000, 0x3000),
]


def ranges(category_prefix: str) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(0x110000 + 1):
        inside = cp <= 0x10FFFF and unicodedata.category(chr(cp)).startswith(category_prefix)
        if inside and start is None:
            start = cp
        elif not inside and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def emit(name: str, rs: list[tuple[int, int]]) -> None:
    print(f"const CodepointRange {name}[] = {{")
    for first, last in rs:
        print(f"    {{0x{first:06X}, 0x{last:06X}}},")
    print("};")
    print(f"const size_t {name[:-6]}RangeCount = sizeof({name}) / sizeof({name}[0]);")
    print()


print(f"// Generated by tools/gen_unicode_tables.py from Unicode {unicodedata.unidata_version}. Do not edit.")
print('#include "tokenizer/unicode_tables.h"')
print()
print("namespace tie {")
print()
emit("kLetterRanges", ranges("L"))
emit("kNumberRanges", ranges("N"))
emit("kWhitespaceRanges", WHITE_SPACE)
print("}  // namespace tie")
